/**
 * Domain types — manually mirrored from specs/openapi.yaml schemas.
 *
 * When the SDK at packages/sdk is generated by nestia, this file should be
 * replaced by `import type { ... } from '@shortflix/sdk'`. Until then we
 * hand-mirror the shapes the FE consumes so build is unblocked.
 */

export type Platform = "YOUTUBE_SHORTS" | "INSTAGRAM_REELS" | "TIKTOK";

export type QuestId =
  | "CARTOGRAPHER"
  | "DIVERSIFIER"
  | "RECEIPT_READER"
  | "TIER_II";

export type AgentId =
  | "ORCHESTRATOR"
  | "CURATOR"
  | "UNIFIED_SEARCH"
  | "TREND_SAFETY";

export interface Pick {
  id: string;
  position: number; // 1..9
  platform: Platform;
  videoUrl: string;
  thumbnailUrl: string;
  durationSec: number;
  region: string; // ISO 3166-1 alpha-2
  sourceLang: string; // BCP-47
  captionLang?: string | null;
  altText: string;
  blurb: string;
  rationale: string;
  noveltyScore: number;
  trendSafetyTags?: string[];
  agentTraceId?: string | null;
}

export interface Issue {
  id: string;
  issueDate: string; // YYYY-MM-DD
  locale: string;
  etag: string;
  publishedAt: string;
  noveltyScore: number;
  picks: Pick[]; // exactly 9
}

export interface QuestProgressItem {
  questId: QuestId;
  progress: number;
  target: number;
  completed: boolean;
  labelKey: string;
  completedAt?: string | null;
}

export interface QuestState {
  forDate: string;
  quests: QuestProgressItem[];
}

export interface Streak {
  currentDays: number;
  longestDays: number;
  lastTickAt?: string;
  freezeTokens?: number;
}

export interface AblationRow {
  droppedAgent: AgentId;
  noveltyScore: number;
  pickOverlap: number;
}

export interface AblationResponse {
  issueDate: string;
  baselineNovelty: number;
  rows: AblationRow[]; // exactly 4
}

export interface Problem {
  type: string;
  title: string;
  status: number;
  detail?: string;
  instance?: string;
  traceId?: string;
  lang?: string;
  errors?: Array<{ field: string; message: string; code?: string }>;
}
